<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fertilizer</name>
  <version>0.0.0</version>
  <description>Package for fertilizer application control using ROS2. This project uses several D555 cameras to detect presence or absence of plants, and block flow of fertilizer accordingly.</description>
  <maintainer email="lsdc@galileo.edu">LSDC</maintainer>
  <license>GPL-3.0-only</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>diagnostic_msgs</depend>
  <depend>opencv_python</depend>
  <depend>python3-yaml</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>realsense2_camera</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
