#amount of fertilizer channels (coils) to control via modbus
n: 5


# Realsense camera configurations
realsense:
  camera1:
    serial: "419222301921"
  camera2:
    serial: "353522302286"
  camera3:
    serial: "409122301544"
  camera4:
    serial: "408222300679"
  camera5:
    serial: "353522301659"
  fps: 15
  color_res:
    x: 640
    y: 360
  infrared_res:
    x: 640
    y: 360
  emulate_tty: true

#ros2 launch configurations
respawn: true
respawn_delay: 5

# Modbus TCP server settings
modbus:
  host: "192.168.11.60"
  port: 502
  auto_open: true
  debounce_time : 500000 # minimum accepted time between the change of coil values

  camera_map :
    camera1 : 0
    camera2 : 1
    camera3 : 2
    camera4 : 3
    camera5 : 5



